# Generated by Django 3.2.8 on 2022-10-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0002_alter_project_id_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
