# Generated by Django 3.2.8 on 2022-10-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0003_project_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='short_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text',
        ),
    ]
