# Generated by Django 3.2.8 on 2022-10-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0004_auto_20221022_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='direction',
            field=models.CharField(default='', max_length=255),
        ),
    ]
