# Generated by Django 3.2.8 on 2022-10-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0005_project_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.CharField(default='Неуказано', max_length=255),
        ),
    ]
