# Generated by Django 3.2.8 on 2022-10-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0006_alter_project_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.CharField(default='Не указано', max_length=255),
        ),
    ]
